#+Title: Incident Management for Operations

Source: [[https://www.amazon.com/Incident-Management-Operations-Rob-Schnepp/dp/1491917628/][https://www.amazon.com/Incident-Management-Operations-Rob-Schnepp/dp/1491917628/]]
Authors: Rob Schnepp, Ron Vidal, Chris Hawley

* Preface
  - Incident Management System (IMS): A framework created in the 70s
    by firefighters to be a simple and effective way to organize a
    team rapidly when bad things happen.
  - Applied to IT oerations because existing practices didn't work well.
  - Like fire operations, IT operations are urgent, so the system
    happened to match well and be a successful application of a cross
    discipline framework.
  - IMS establishes the framework of incident response and the norms
    of behavior for the incident responders
* Evaluating the Incident Response PROCESS
  - Definition of *incident*: An occurrence, either human-caused or a
    natural phenomenon that requires action or support by emergency
    services personnel to prevent or minimize loss of life or damage
    to property and/or natural resources.
    - For IT: An unplanned interruption to an IT service or reduction
      in the quality of an IT Service.
  - AAR: After Action Review (e.g. a Retrospective)
  - Develop a list of questions that can be asked and answered both
    quantitatively and qualitatively
    - Establish baseline data to evaluate improvements
  - "Is there one person here who understands the entire stack in great detail to fix any issue that may occur?"
  - As the stack evolves, so too should the incident management
    process as specialized problem solvers will be required.
  - Definition of *event*: A point-in-time fact relevant to the
    operations of your infrustructure or application (e.g. CPU cross
    the 95% threshold on host abc), but which is not considered an
    incident. May become an incident.
  - Incident response is a team sport that depends on strong
    leadership and a capable team of technical experts. The pace at
    which they assemble and begin resolution is different than
    completing a sprint or some other nonincident related task.
  - PROCESS stands for Predictable, Repeatable, Optimized, Clear,
    Evaluated, Scalable, and Sustainable.
  - Many companies don't define a clear distinction between:
    - Notification: A message sent to a person. Intended to be FYI
      rather than a dispatch, which is an order.
    - Dispatch: The action of reaching out to a particular person
      representing a job function. An Order, not a request.
    - Alert: Represents the state of a monitoring tool check/condition
      initiated/resolved by an event. Generated by monitoring
      tools. Possibly the first point in time that an event is
      identified.
  - *If you are an IT incident responder, TIME is the most important commodity that exists.*
  - The wrong question to ask during an incident is *why it
    broke*. Ask *how do we fix it?*
  - Focus on the Mean Time To Assemble, as you won't have good Mean
    Time To Resolution without good MTTAs!
  - Restore service: "Why you put out the fire, conditions get better."
  - MTTA is the only activity controlled by the Incident Response Team.
  - *Predictability* in incident response is about clarity of roles
    and responsibilities and the expected behavior of each person
    before and after they are assembled for an incident.
    - If you are identified to be "on-call" it is *not* optional.
  - *Repeatable* is the "how" part of the response. The goal is
    consistently and efficiently dispatching the people identified in
    the predictability section.
    - Helps to have a list, with SEV levels of possible / likely
      incidents, their SMEs, etc.
    - Repeatable is ensuring the responders respond the same way every
      time, and are truly available.
  - !!!!! *Optimized* *builds upon a predictable and repeatable incident response mechanism by ensuring the identified responders understand the rules of engagement during incidents and are trained, equipped, and clearly prepared to do what is being asked of them.*
    - Escalation: the addition of more or different resources, beyond
      the initial dispatch.
    - !!!!! Is the importance of incident response being explained to
      on call members?
    - !!!!! Were they trained in their individual and team roles in
      incident response?
  - *Clarity* ensures that general programmatic and incident response goals and objectives are conveyed to all IRT members and all others that may participate in response. It's easy to assume that all who might join an incident response in any capacity are clear about the goals and objectives of the incident resolution effort. But, this isn't always the case. (it needs to be)
    - Critical that anyone summoned knows *exactly* why they are being summoned, what their role will be, and when they will be released from the incident by the IC.
    - !!!!! Executives should strive to build a culture of incident
      response, ensuring predictability, repeatability, and
      optimization of the team.
    - MUST BE BAKED INTO THE COMPANIES CULTURE.
    - !!!!! Do all responders really understand that they are
      functioning as a fire department?
    - Incident responders should be defending the business from harm.
  - *Evaluated* Retrospectives. Evaluate and tweak the process. Address weaknesses.
    - WHen you uncover "landmines" of poor or inconsistent
      performance, you must identify them, ack them, and do what it
      takes to improve the deficiency!
    - Poor performance may become the established norma, and
      culturally, it will be difficult to change down the road.
  - *Scalable* The scalable part of the process is linked to
    predictability and repeatability in that a sound incident response
    process and quickly grow and shrink depending on the needs of the
    incident or growth of the organization.
    - What is the *bench strength*? 
    - Ideally, the IRT establishes its identity and available resources by function. That way it's not dependent on only a handful of people to respond on a regular basis.
  - *Sustainable* When incident response passes the point of initial training and becomes a formal activity within the organization, the organization must view, care for, and value the IRT just like any other business unit.
    - IRT should not be viewed as "necessary evil."
  - There should be no doubt abot who is available to respond and who is available in the incident response talent pool.
  - Everyone on the IRT should know *exactly* what is expected of them, what their role is, what latitude they have to make decisions on an incident, and know that they have support from execs to resolve incidents to protect the business.
* Incident Management System (IMS)
  - A fire in 1970 resulted in 13 days of fires, 13 fatalities, and
    700 destroyed homes.
    - Thousands of firefighters from around the state and beyond
      responded, but found it difficult to work together.
    - They knew how to fight fires, but lacked a common management
      framework that could scale.
    - Lacked a standard approach for incident leadership.
  - IMS was revolutionary because it cut across geographical and
    cultural boundaries that separate fire departments.
  - It overcame the political inertia and resistence to change that
    could have killed it off as a fad or "something that just won't
    work for us"
  - Works because it's a flexible, scalable approach baked into the
    culture of the company and responders in order to provide the
    leadership and management to preditably and efficiently respond to
    all-hazard, all-risk events.
  - Applied to IT, the most useful components of IMS:
    - Establish a single point of leadership
    - Framework to manage and keep track of responders
    - Provides platform to standardize job functions and terminology
      used by responders.
  - A burning building and an IT incident create *downtime*, and the
    incident responders are there to return the situation to *uptime*.
  - !!!!! There's a different in *responding* and *reacting* to an incident.
    - Responders are trained, organized, and disciplined in their approach to resolving the incident.
      - Cool, calm, and collected and can think clearly under pressure. 
    - Reactors tend to be emotional and without discipline, either as individuals or a team.    
      - Get emotional and irrational. Arrive to see an *emergency* not an incident.
  - "Fire is not an emergency to the fire department. It's what we do." 
  - Incident response is a people-to-people activity. The attitudes and demeanor of the people and how they work together as a team is vital.
  - !!!!! When an incident occurs, all individuals responsible for
    resolving the incident must shift his or her thinking and decision
    making from *peacetime* to *wartime* and immediately transition
    from being day-to-day technical resource *for* the company, to
    incident responder tasked with *defending* the company.
    - *Peacetime* is the steady state environment of continuing operations that exists in nonincdent mode. Peacetime is uptime.
    - *Wartime* is an urgent, degraded mode of operation that occurs when any application or infrastructure element experiences an issues outside the normal course of business. Wartime is downtime.
  - Think of incident response as a really fast and compressed sprint ... in the Agile sense.
  - Can't resolve incidents with just a strong leader. Need technical expertise. Converse is true.
  - SEV level is critical because it can be used to determine who initially responds to the incident and/or what type of SME such as network, database, or storage might be needed to provie technical expertise.
  - When responding as an SME, a non-exhaustive list of things: 
    - Don't let the IC fail 
    - Identify with name, and function.
    - Wait for briefing or other instructions from the IC
    - Ensure that your work environment is quiet (more for voice bridge)
    - Speak up and clearly
    - Be specific, and factual at all times
    - Respect the IC's timeline
    - Answer directly the probing questions you may be asked in order to come up with a realistic solution.
    - Have backup plans in addition to you primary plan.
    - If you need more help, *ask* for it.
  - IC is a function filled by a person. Doesn't mean it has to be the *same* person, always.
  - IC can be anyone in the organization as long as they've trained to be an IC and understand what's expected of them, and demonstrate competence.
  - Efficient Incident Response is achieved (graphically):
      PS = Problem Sovling Talent
            (IMS + IC) + PS 
      EIR = ---------------
                 Time
  - Time is the one resource you can never reclaim. It can't be created. It can only be saved or wasted.
  - The IC should:
    - Ensure the responders have a clear understanding of the issue
    - Set clear indicent resolution objectives.
    - Work with SMEs to interpret key metrics from monitoring tools to facilitate a discussion aimed at building an action plan
    - Keep an eye on the clock and keep the reoslution effort on track and moving forward
    - Have access to a pool of resources
    - Establish reliable comms methods
    - Provide information to key players in a timely manner.
  - Large part of IC is keeping the participants focused on incident response objectives.
  - Failure generates data. hestiation by an IC generates FUD.
  - Everyone on the IRT reports to the IC.
  - An IC with specific technical expertise needs to be careful as they may be likely to act as an SME.
  - When an incident occurs, all individuals responsible for resolving the incident must immediately shift focus, thinking and decision making, and operational posture from peacetime to wartime.
  - Solving wartime incidents requires a wartime mentality, behavioral patterns, and organizational structure.
  - The first key principle of incident response, and the cornerstone of the IMS, is that every incident response must have leadership.
  - Everyone must work as a team for it to work.
  - Overall goal of incident response is to resolve the incident as quickly and efficiently as possible in order to return the operations of the company to business-as-usual, or peacetime state.
  - There are many possible job functions that could be established by an IRT. Customize IMS to fit your need.
        
